[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
extra_scripts = pre:scripts/upload_all.py
lib_deps =
    bblanchon/ArduinoJson@^7
    adafruit/Adafruit PN532@^1

[env:calib]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = -<*> +<../calib_src/>
